import {
  faEnvelope,
  faExternalLinkSquareAlt,
  faMobileAlt,
  faDesktop,
  faCheck,
  faTimes,
  faChevronDown,
  faExpand,
  faLock,
  faUnlock,
  faEnvelopeOpen,
  faSignInAlt,
  faSignOutAlt,
  faPlus,
  faTrash,
  faEdit,
} from "@fortawesome/free-solid-svg-icons";
import {
  faGithub,
  faInstagram,
  faFlickr,
  faStrava,
  faLinkedin,
} from "@fortawesome/free-brands-svg-icons";

export const icons = {
  faEnvelope,
  faGithub,
  faInstagram,
  faFlickr,
  faLinkedin,
  faStrava,
  faExternalLinkSquareAlt,
  faMobileAlt,
  faDesktop,
  faCheck,
  faTimes,
  faChevronDown,
  faExpand,
  faLock,
  faUnlock,
  faEnvelopeOpen,
  faSignInAlt,
  faSignOutAlt,
  faPlus,
  faTrash,
  faEdit,
};
