name: Test output

on:
  workflow_dispatch:

jobs:
  create-output:
    name: Test output
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Prepare changelog
        id: changelog
        run: |
          echo 'JSON_RESPONSE<<EOF' >> $GITHUB_ENV
          curl https://example.lab >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: print output
        id: print-output
        run: echo ${{ steps.changelog.outputs.EOF }}
