name: Test output

on:
  workflow_dispatch:

jobs:
  create-output:
    name: Test output
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Prepare changelog
        id: changelog
        run: |
          changelog="Please check GitHub for full list of changes and people to ping for. "$'\n\n'"sha: asdasdasda"$'\n\n'"full diff: full-diff-here"$'\n\n'"${changelog}"
          echo "changelog=$changelog" >> $GITHUB_OUTPUT
      - name: print output
        id: print-output
        run: echo ${{ steps.changelog.outputs.changelog }}
