name: Draft release

on:
  workflow_dispatch:

jobs:
  create-draft-release:
    name: Draft release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Prepare changelog
        id: changelog
        run: |
          changelog="Please check GitHub for full list of changes and people to ping for. "$'\n\n'""
          changelog="${changelog//$'\n'/'%0A'}"
          echo "changelog=$changelog" >> $GITHUB_OUTPUT
