name: Test output

on:
  workflow_dispatch:

jobs:
  create-output:
    name: Test output
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Prepare changelog
        id: changelog
        run: |
          compare="this-is-compare"
          sha="this-is-sha"
          changelog="Please check GitHub for full list of changes and people to ping for. "$'\n\n'" sha: ${sha} "$'\n\n'" full diff: ${compare} "$'\n\n'"${changelog}"
          echo "changelog=$changelog" >> $GITHUB_OUTPUT
      - name: print output
        id: print-output
        run: echo ${{ steps.changelog.outputs.changelog }}
